name: retrofit_flutter
description: retrofit for flutter
version: 1.0.6
homepage: https://github.com/zhuchunyao/retrofit_flutter

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  dio: ^5.3.2
  source_gen: ^1.2.2
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  analyzer: ^6.2.0
  dart_style: ^2.2.1
  build: ^2.0.0
  collection: ^1.15.0